version: '2'
services:
    agrobourse360si-app:
        image: agrobourse360si
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://agrobourse360si-postgresql:5432/AgroBourse360SI
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=agrobourse360si-elasticsearch:9300
        ports:
            - 8080:8080
    agrobourse360si-postgresql:
        extends:
            file: postgresql.yml
            service: agrobourse360si-postgresql
    agrobourse360si-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: agrobourse360si-elasticsearch
