version: '2'
services:
    agrobourse360si-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/AgroBourse360SI/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=AgroBourse360SI
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
